# Generated by Django 5.0.2 on 2024-03-17 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userReporting', models.CharField(max_length=20)),
                ('pub_date', models.CharField(max_length=20)),
                ('report_type', models.CharField(max_length=20)),
                ('description', models.CharField(max_length=200)),
                ('file', models.CharField(max_length=20)),
            ],
        ),
    ]
