# Generated by Django 5.0.2 on 2024-03-26 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bgmaintenance', '0002_remove_report_file_report_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='description',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='report',
            name='report_type',
            field=models.CharField(choices=[('Toilet', 'TOILET'), ('Window', 'WINDOW'), ('Sink', 'SINK'), ('Other', 'OTHER')], max_length=20),
        ),
    ]
