# Generated by Django 5.0.2 on 2024-03-26 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bgmaintenance', '0003_alter_report_description_alter_report_report_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='report_type',
            field=models.CharField(max_length=20),
        ),
    ]
