# Generated by Django 5.0.2 on 2024-03-27 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bgmaintenance', '0005_comment_pub_date_alter_report_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='file',
        ),
        migrations.AddField(
            model_name='file',
            name='file_name',
            field=models.CharField(default=2, max_length=60),
            preserve_default=False,
        ),
    ]
