# Generated by Django 5.0.2 on 2024-03-27 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bgmaintenance', '0006_remove_file_file_file_file_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='file_name',
        ),
        migrations.AddField(
            model_name='file',
            name='file',
            field=models.FileField(default=2, upload_to=''),
            preserve_default=False,
        ),
    ]
