# Generated by Django 5.0.2 on 2024-04-11 04:46

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bgmaintenance', '0007_remove_file_file_name_file_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='pub_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='report',
            name='userReporting',
            field=models.CharField(max_length=50),
        ),
    ]
