# Generated by Django 5.0.2 on 2024-04-11 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bgmaintenance', '0008_alter_report_pub_date_alter_report_userreporting'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='pub_date',
            field=models.DateTimeField(),
        ),
    ]
