# Generated by Django 5.0.2 on 2024-04-14 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bgmaintenance', '0011_alter_report_pub_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='username',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='report',
            name='report_type',
            field=models.CharField(choices=[('LOCKED', 'Locked Out of Dorm'), ('PLUMBING', 'Plumbing'), ('WINDOW', 'Window'), ('ELECTRICAL', 'Electrical Issues'), ('FURNITURE', 'Broken Furniture'), ('APPLIANCES', 'Appliances'), ('SECURITY', 'Room Security (Broken Lock etc.)'), ('HVAC', 'HVAC'), ('INSECTS', 'Insects'), ('OTHER', 'Other (please describe)')], max_length=20),
        ),
    ]
