# Generated by Django 5.0.4 on 2024-04-19 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bgmaintenance', '0012_alter_comment_username_alter_report_report_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='area',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='report',
            name='building',
            field=models.CharField(blank=True, choices=[('ALD', 'Alderman Library'), ('ART', 'Art Library')], max_length=50),
        ),
    ]
