# Generated by Django 5.0.4 on 2024-04-22 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bgmaintenance', '0013_report_area_report_building'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='building',
            field=models.CharField(blank=True, choices=[('ALD', 'Alderman Library'), ('AQC', 'Aquatic and Fitness Center'), ('AST', 'Astronomy Building'), ('BGC', 'Birdwood Golf Course'), ('BOND', 'Bond House'), ('BMU', 'Bayly Building'), ('BRK', 'Brooks Hall'), ('BRN', 'Bryan Hall'), ('BRO', 'Brown College Library'), ('BRY', 'Bryant Hall'), ('CAB', 'New Cabell Hall'), ('CAM', 'Campbell Hall'), ('CAU', 'Cauthen House'), ('CDW', 'Clinical Department Wing'), ('CHE', 'Chemical Engineering Building'), ('CMN', 'Claude Moore Nursing'), ('COB', 'Cobb Hall'), ('COC', 'Cocke Hall'), ('CHM', 'Chemistry Building'), ('CLK', 'Clark Hall'), ('CLM', 'Clemons Library'), ('DR1', "Dawson's Row Residence 1"), ('DRM', 'Drama Education Building'), ('DVS', 'Hospital West, Davis Wing'), ('FHL', 'Fayerweather Hall'), ('FRN', 'French House'), ('GIB', 'Gibson Hall'), ('GIL', 'Gilmer Hall'), ('GSB', 'Darden School'), ('HAL', 'Halsey Hall'), ('HOD', 'Hotel D, East Range'), ('HOM', 'Home of the Instructor'), ('HSBB', 'Hunter Smith Band Building'), ('ICE', 'Charlottesville Ice Park'), ('JAG', 'Judge Advocate General School'), ('JOR', 'Jordan Hall'), ('JSR', 'Jesser Hall'), ('KER', 'Kerchof Hall'), ('LACY', 'Lacy Hall'), ('LEV', 'Levering Hall'), ('LHO', 'Lambeth House'), ('LPJ', 'Luther P. Jackson House'), ('LWO', 'Lower West Oval Room, Rotunda'), ('MCL', 'McLeod Hall'), ('MEC', 'Mechanical Engineering Building'), ('MED', 'Old Medical School'), ('MGM', 'Memorial Gymnasium'), ('MHP', 'Multistory Building (Old Hospital)'), ('MH3', 'Monroe Hill Range'), ('MIN', 'Minor Hall'), ('MON', 'Monroe Hall'), ('MSB', 'Materials Science Building'), ('MUN', 'Mary Munford House'), ('NAU', 'Nau Hall'), ('NHL', 'Newcomb Hall'), ('OBS', 'McCormick Observatory'), ('OCH', 'Old Cabell Hall'), ('OLS', 'Olsson Hall'), ('PBY', 'Peabody Hall'), ('PHS', 'Physics Building'), ('PV5', 'Pavilion V'), ('PV8', 'Pavilion VIII'), ('RAN', 'Randall Hall'), ('RAO', 'National Radio Astronomy Observatory'), ('RBT', 'Robertson Hall'), ('RDL', 'Ridley Hall (previously known as RFN Ruffner)'), ('REA', 'Nuclear Reactor'), ('REC', 'Slaughter Recreation Center'), ('RICE', 'Rice Hall'), ('RSH', 'Rouss Hall'), ('RTN', 'Rotunda'), ('RUF', 'Ruffin Hall'), ('SHH', 'Shea House'), ('SHN', 'Shannon House'), ('SHW', 'Student Health and Wellness'), ('SLH', 'Slaughter Hall'), ('STB', 'Barracks Stables'), ('STC', 'Stacey Hall'), ('THN', 'Thornton Hall'), ('WIL', 'Wilson Hall'), ('WNR', 'Warner Hall'), ('WSB', 'Withers-Brown Hall'), ('ZMA', 'Zehmer Hall Annex'), ('ZMR', 'Zehmer Hall')], max_length=50),
        ),
    ]
